#LED pin
set_property IOSTANDARD LVCMOS33 [get_ports {led_pl_tri_o[0]}]
set_property PACKAGE_PIN AE12 [get_ports {led_pl_tri_o[0]}]

# DDR pins
set_property PACKAGE_PIN AH4 [get_ports {ddr4_pl_odt[0]}]
set_property PACKAGE_PIN AE8 [get_ports {ddr4_pl_bg[0]}]
set_property PACKAGE_PIN AB5 [get_ports {ddr4_pl_adr[16]}]
set_property PACKAGE_PIN AB7 [get_ports {ddr4_pl_adr[15]}]
set_property PACKAGE_PIN AF6 [get_ports {ddr4_pl_adr[14]}]
set_property PACKAGE_PIN AD9 [get_ports {ddr4_pl_adr[13]}]
set_property PACKAGE_PIN AC6 [get_ports {ddr4_pl_adr[12]}]
set_property PACKAGE_PIN AH9 [get_ports {ddr4_pl_adr[11]}]
set_property PACKAGE_PIN AE7 [get_ports {ddr4_pl_adr[10]}]
set_property PACKAGE_PIN AC9 [get_ports {ddr4_pl_adr[9]}]
set_property PACKAGE_PIN AH8 [get_ports {ddr4_pl_adr[8]}]
set_property PACKAGE_PIN AE9 [get_ports {ddr4_pl_adr[7]}]
set_property PACKAGE_PIN AH7 [get_ports {ddr4_pl_adr[6]}]
set_property PACKAGE_PIN AD7 [get_ports {ddr4_pl_adr[5]}]
set_property PACKAGE_PIN AF7 [get_ports {ddr4_pl_adr[4]}]
set_property PACKAGE_PIN AC8 [get_ports {ddr4_pl_adr[3]}]
set_property PACKAGE_PIN AF8 [get_ports {ddr4_pl_adr[2]}]
set_property PACKAGE_PIN AB8 [get_ports {ddr4_pl_adr[1]}]
set_property PACKAGE_PIN AG8 [get_ports {ddr4_pl_adr[0]}]
set_property PACKAGE_PIN AD2 [get_ports {ddr4_pl_dqs_t[1]}]
set_property PACKAGE_PIN AD1 [get_ports {ddr4_pl_dqs_c[1]}]
set_property PACKAGE_PIN AE2 [get_ports {ddr4_pl_dqs_t[0]}]
set_property PACKAGE_PIN AF2 [get_ports {ddr4_pl_dqs_c[0]}]

set_property PACKAGE_PIN AC4 [get_ports {ddr4_pl_dq[15]}]
set_property PACKAGE_PIN AC3 [get_ports {ddr4_pl_dq[14]}]
set_property PACKAGE_PIN AB4 [get_ports {ddr4_pl_dq[13]}]
set_property PACKAGE_PIN AB3 [get_ports {ddr4_pl_dq[12]}]
set_property PACKAGE_PIN AB2 [get_ports {ddr4_pl_dq[11]}]
set_property PACKAGE_PIN AC2 [get_ports {ddr4_pl_dq[10]}]
set_property PACKAGE_PIN AB1 [get_ports {ddr4_pl_dq[9]}]
set_property PACKAGE_PIN AC1 [get_ports {ddr4_pl_dq[8]}]
set_property PACKAGE_PIN AG3 [get_ports {ddr4_pl_dq[7]}]
set_property PACKAGE_PIN AH3 [get_ports {ddr4_pl_dq[6]}]
set_property PACKAGE_PIN AE3 [get_ports {ddr4_pl_dq[5]}]
set_property PACKAGE_PIN AF3 [get_ports {ddr4_pl_dq[4]}]
set_property PACKAGE_PIN AH2 [get_ports {ddr4_pl_dq[3]}]
set_property PACKAGE_PIN AH1 [get_ports {ddr4_pl_dq[2]}]
set_property PACKAGE_PIN AF1 [get_ports {ddr4_pl_dq[1]}]
set_property PACKAGE_PIN AG1 [get_ports {ddr4_pl_dq[0]}]

set_property INTERNAL_VREF 0.6 [get_iobanks 64]

set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_clk_p]
set_property PACKAGE_PIN AE5 [get_ports c0_sys_clk_clk_p]
set_property PACKAGE_PIN AF5 [get_ports c0_sys_clk_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_clk_n]

set_property PACKAGE_PIN AB6 [get_ports {ddr4_pl_cs_n[0]}]
set_property PACKAGE_PIN AG6 [get_ports {ddr4_pl_ck_t[0]}]
set_property PACKAGE_PIN AG5 [get_ports {ddr4_pl_ck_c[0]}]
set_property PACKAGE_PIN AE4 [get_ports {ddr4_pl_cke[0]}]
set_property PACKAGE_PIN AG9 [get_ports ddr4_pl_reset_n]
set_property PACKAGE_PIN AD4 [get_ports ddr4_pl_act_n]
set_property PACKAGE_PIN AC7 [get_ports {ddr4_pl_ba[1]}]
set_property PACKAGE_PIN AH6 [get_ports {ddr4_pl_ba[0]}]
set_property PACKAGE_PIN AD5 [get_ports {ddr4_pl_dm_n[1]}]
set_property PACKAGE_PIN AG4 [get_ports {ddr4_pl_dm_n[0]}]




